language: python
python:
  - "2.6"
  - "2.7"

install:
 - pip install -r requirements.txt --use-mirrors
 - pip install coverage coveralls

script:
  - coverage run --source=s3tos3backup setup.py test

after_success:
  - coverage report --omit="tests/*" -m
  - coveralls

notifications:
  email:
    recipients:
      - team@ydtechnology.com
